### ISSUE TITLE
Denoise feature is not working on IDZPrecompiledSpeex

### ISSUE THREAD

**Issue by tarzan0420** [iosdevzone/IDZPrecompiledSpeex#3]
I am sure that the recorded voice is successfully denoised on android app using Speex sources.
So, I would like to denoise voice on iphone app, too.

I am a beginner in developing IPhone app with Swift.
So, I am not sure whether or not it is from my developing skill or this precompiled speex framework issue.
But I think that I have done exactly and can see audio data changes between before and after Speex Process.

I am afraid to upload my messy project files, but i would like to get recommended from Speex experts about my source codes.

I am looking forward for good comments now.

Thanks.

[Speex Issue.zip](https://github.com/iosdevzone/IDZPrecompiledSpeex/files/4328899/Speex.Issue.zip)

**Comment by iosdevzone** [comment]
The latest version of Speex, v1.2.0, moves all preprocessing into a separate library, speexDSP. So the current version does not support what you are trying to do. You could:
1) Use the process described in the README.md to compile an older version.
2) Try to compile speexDSP yourself.

When looking for help with code, it's a good idea to provide minimal example of what's not working, and some explanation of what you think is wrong. You haven't really provided either above. Also, GitHub issues are generally for bugs in the project themselves. If you need code help, you may get better results posting on StackOverflow.
